# Lint, Build, Test - Go

name: Go - Lint-Build-Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.24.1' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: make install
      - name: Lint Go
        run: make lint-check
      - name: Build Go
        run: make build
      - name: Test Go
        run: make test
